set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(TARGET_PLATFORM_ROOTFS "/home/dongger/rpi_rootfs")

set(CMAKE_C_COMPILER aarch64-linux-gnu-gcc-8)
set(CMAKE_CXX_COMPILER aarch64-linux-gnu-g++-8)
# set(CMAKE_CXX_LINK_EXECUTABLE "aarch64-linux-gnu-ld <CMAKE_CXX_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")

set(DEPENDENCY_LIBRARIES_ROOTDIR "/sources")

if(NOT BUILD_JSONCPP)
	set(CMAKE_C_COMPILER_ID GNU CACHE STRING "")
	set(CMAKE_CXX_COMPILER_ID GNU CACHE STRING "")
endif()

if(TARGET_PLATFORM_ROOTFS)
	set(CMAKE_FIND_ROOT_PATH ${TARGET_PLATFORM_ROOTFS})
	set(CMAKE_SYSROOT ${TARGET_PLATFORM_ROOTFS})
endif()

# set(CMAKE_C_COMPILE_OPTIONS_SYSROOT "--sysroot=")
# set(CMAKE_CXX_COMPILE_OPTIONS_SYSROOT "--sysroot=")

add_definitions("--sysroot=${TARGET_PLATFORM_ROOTFS}")
if(NOT SYSROOT_HAS_SET)
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} --sysroot=${TARGET_PLATFORM_ROOTFS} --std=c++17" CACHE INTERNAL "" FORCE)
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} --sysroot=${TARGET_PLATFORM_ROOTFS}" CACHE INTERNAL "" FORCE)
	set(SYSROOT_HAS_SET 1)
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
